name: Check

on:
  push:
    branches:
      - main
      - next
    paths-ignore:
      - docs/**
  pull_request:
    branches:
      - main
      - next

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max_old_space_size=6144

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get list of changed files
        id: changes
        run: echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Run Linter on changed files
        run: |
          changed_files="${{ steps.changes.outputs.files }}"
          if [ -n "$changed_files" ]; then
            pnpm exec eslint $changed_files
          else
            echo "No changed files to lint."
          fi

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get list of changed files
        id: changes
        run: echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"

      - name: Prepare
        uses: ./.github/actions/prepare
        with:
          build: false

      - name: Run Formatter on changed files
        run: |
          changed_files="${{ steps.changes.outputs.files }}"
          if [ -n "$changed_files" ]; then
            pnpm exec prettier --check $changed_files
          else
            echo "No changed files to format."
          fi

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Run Tests
        run: pnpm test

  analyze:
    name: CodeQL Analysis
    uses: ./.github/workflows/codeql-analysis.yml
